import type {Metadata} from "next";
import {Geist, Geist_Mono} from "next/font/google";
import {ThonLabsWrapper} from "@thonlabs/nextjs";
import Header from "./_components/header";
import {isThonLabsRoute} from "@thonlabs/nextjs/server";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default async function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	const isAuthRoute = await isThonLabsRoute();

	return (
		<html lang="en" suppressHydrationWarning>
			<body className={`${geistSans.variable} ${geistMono.variable}`}>
				<ThonLabsWrapper
					environmentId={process.env.NEXT_PUBLIC_TL_ENV_ID as string}
					publicKey={process.env.NEXT_PUBLIC_TL_PK as string}
					authDomain={process.env.NEXT_PUBLIC_TL_AUTH_DOMAIN as string}
				>
					{!isAuthRoute && <Header />}
					{children}
				</ThonLabsWrapper>
			</body>
		</html>
	);
}
